### PR TITLE
Naz

### PR DESCRIPTION
**Pull request by natebell510**
Naz Branch created,  TestClass created, note 1 and note 2 added

### CODE REVIEW

**Review by BadamkhandB — APPROVED** [review]
Looks pretty good!

**Review by Aramat16ukr — APPROVED** [review]
double checked all good

**Review by VeronikaKrasnokutska — CHANGES_REQUESTED** [review]
add note 2,please

**Review by Idemianiv — APPROVED** [review]
looks great

**Review by VeronikaKrasnokutska — APPROVED** [review]

**Review by LaylaNait — COMMENTED** [review]
great jobe

**Review by ZaierAouani — APPROVED** [review]

**Review by VeronikaKrasnokutska — APPROVED** [review]

**Pull request merged**
