### PR TITLE
Tamara

### PR DESCRIPTION
**Pull request by Aramat16ukr**
i'm done with my work

### CODE REVIEW

**Review by LaylaNait — APPROVED** [review]
good jobe

**Review by LaylaNait — APPROVED** [review]
good jobe

**Comment by ZaierAouani** [comment]
Great!

**Review by BadamkhandB — CHANGES_REQUESTED** [review]
in my opinion, You need to give us more examples on your code.

**Review by Idemianiv — APPROVED** [review]
good

**Review by AnnaLoshak — APPROVED** [review]
Looks good

**Review by Aramat16ukr — COMMENTED** [review]
review

**Review by BadamkhandB — APPROVED** [review]

**Review by natebell510 — COMMENTED** [review]
Nice!

**Review by VeronikaKrasnokutska — APPROVED** [review]

**Review by VeronikaKrasnokutska — APPROVED** [review]

**Review by ZaierAouani — APPROVED** [review]

**Pull request merged**
